import React from 'react';
import Document, { Html, Head, Main, NextScript, DocumentContext, DocumentInitialProps } from 'next/document'

class MyDocument extends Document {
    static async getInitialProps(
        ctx: DocumentContext
    ): Promise<DocumentInitialProps> {
        const initialProps = await Document.getInitialProps(ctx)
        return {
            ...initialProps,
            styles: React.Children.toArray([initialProps.styles])
        };
    }
    //<link href="https://fonts.cdnfonts.com/css/poppins" rel="stylesheet" />
    render() {
        return (
            <Html lang={"es"}>
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <body>
                <Main />
                <NextScript />
                  <div id="modal-root"></div>
                </body>
            </Html>
        )
    }
}

export default MyDocument